### ISSUE TITLE
¿Como se levanta el ejemplo?

### ISSUE THREAD

**Issue by gastonambrogi** [sljavi/intro-web-speech-api#1]
Eso, como levantas el ejemplo, revisando los archivos, no entiendo como lo levantas localmente. Gracias.

**Comment by sljavi** [comment]
Hola,

Lo podés levantar haciendo

```
git clone git@github.com:sljavi/intro-web-speech-api.git
cd intro-web-speech-api
npm install
```

Opción 1
`npm run prod`

Opción 2
`npm run dev`

En breve actualizo el readme para dar una explicación más detallada

Gracias!!

**Comment by sljavi** [comment]
Actualizado: https://github.com/sljavi/intro-web-speech-api/blob/master/README.md
